# Generated by Django 5.0 on 2023-12-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appOutfitShowroom", "0004_estilo_nombre_en_ocasion_nombre_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("fecha_nacimiento", models.DateField()),
                ("email", models.CharField(max_length=50)),
                ("telefono", models.IntegerField()),
            ],
        ),
    ]
