# Generated by Django 4.2.7 on 2023-12-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutfitShowroom', '0005_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='autor',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
