# Generated by Django 4.2.7 on 2023-11-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutfitShowroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Image'),
        ),
    ]
