# Generated by Django 4.2.7 on 2023-12-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOutfitShowroom', '0002_alter_outfit_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='estilo',
            new_name='estilos',
        ),
    ]
