# Generated by Django 4.2.6 on 2023-11-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estilo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ocasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Outfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(max_length=700)),
                ("precio", models.IntegerField(default=0)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="img", verbose_name="Image"
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("estilo", models.ManyToManyField(to="appOutfitShowroom.estilo")),
                (
                    "ocasion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appOutfitShowroom.ocasion",
                    ),
                ),
            ],
        ),
    ]
