# Generated by Django 4.2.6 on 2023-12-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appOutfitShowroom", "0003_rename_estilo_outfit_estilos"),
    ]

    operations = [
        migrations.AddField(
            model_name="estilo",
            name="nombre_en",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ocasion",
            name="nombre_en",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="outfit",
            name="descripcion_en",
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name="outfit",
            name="nombre_en",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
